[2023-03-26T21:39:14.959+0200] {processor.py:153} INFO - Started process (PID=16635) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:39:14.960+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:39:14.961+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:39:14.961+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:39:14.978+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:39:14.978+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:39:14.979+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:39:14.979+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:39:14.979+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:39:14.985+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-03-26T21:40:16.637+0200] {processor.py:153} INFO - Started process (PID=16727) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:40:16.637+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:40:16.638+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:40:16.638+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:40:16.653+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:40:16.653+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:40:16.654+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:40:16.654+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:40:16.654+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:40:16.661+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-03-26T21:41:07.706+0200] {processor.py:153} INFO - Started process (PID=16779) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:41:07.738+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:41:07.739+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:41:07.739+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:41:07.757+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:41:07.756+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:41:07.757+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:41:07.757+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:41:07.757+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:41:07.765+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2023-03-26T21:47:51.173+0200] {processor.py:153} INFO - Started process (PID=16832) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:47:51.197+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:47:51.198+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:47:51.197+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:47:51.213+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:47:51.213+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:47:51.213+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:47:51.213+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:47:51.213+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:47:51.220+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-03-26T21:48:38.479+0200] {processor.py:153} INFO - Started process (PID=16912) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:48:38.491+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:48:38.492+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:48:38.491+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:48:38.509+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:48:38.508+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:48:38.509+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:48:38.509+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:48:38.509+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:48:38.517+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-26T21:49:29.832+0200] {processor.py:153} INFO - Started process (PID=16954) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:49:29.845+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:49:29.846+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:49:29.846+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:49:29.861+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:49:29.860+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:49:29.861+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:49:29.861+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:49:29.861+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:49:29.869+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-03-26T21:50:14.204+0200] {processor.py:153} INFO - Started process (PID=16998) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:50:14.239+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:50:14.240+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:50:14.240+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:50:14.257+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:50:14.257+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:50:14.258+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:50:14.258+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:50:14.258+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:50:14.265+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-03-26T21:50:59.398+0200] {processor.py:153} INFO - Started process (PID=17079) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:50:59.399+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:50:59.399+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:50:59.399+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:50:59.415+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:50:59.415+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:50:59.416+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:50:59.416+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:50:59.416+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:50:59.424+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-03-26T21:51:44.821+0200] {processor.py:153} INFO - Started process (PID=17158) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:51:44.861+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:51:44.862+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:51:44.861+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:51:44.879+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:51:44.879+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:51:44.880+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:51:44.880+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:51:44.880+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:51:44.888+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2023-03-26T21:52:33.108+0200] {processor.py:153} INFO - Started process (PID=17201) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:52:33.109+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:52:33.110+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:52:33.110+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:52:33.126+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:52:33.125+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:52:33.126+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:52:33.126+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:52:33.126+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:52:33.133+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-03-26T21:53:21.865+0200] {processor.py:153} INFO - Started process (PID=17250) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:53:21.866+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:53:21.867+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:53:21.866+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:53:21.880+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:53:21.879+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:53:21.880+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:53:21.880+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:53:21.880+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:53:21.887+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-03-26T21:54:11.133+0200] {processor.py:153} INFO - Started process (PID=17303) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:54:11.156+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:54:11.157+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:54:11.156+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:54:11.171+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:54:11.171+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:54:11.171+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:54:11.171+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:54:11.171+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:54:11.180+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-03-26T21:55:00.821+0200] {processor.py:153} INFO - Started process (PID=17347) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:55:00.859+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:55:00.860+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:55:00.860+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:55:00.874+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:55:00.874+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:55:00.874+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:55:00.874+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:55:00.874+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:55:00.884+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-03-26T21:55:50.655+0200] {processor.py:153} INFO - Started process (PID=17407) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:55:50.685+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:55:50.686+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:55:50.686+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:55:50.792+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:55:50.791+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:55:50.792+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:55:50.792+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:55:50.792+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:55:50.797+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.144 seconds
[2023-03-26T21:56:37.450+0200] {processor.py:153} INFO - Started process (PID=17491) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:56:37.488+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:56:37.489+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:56:37.489+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:56:37.503+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:56:37.502+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:56:37.503+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:56:37.503+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:56:37.503+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:56:37.512+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-03-26T21:57:21.085+0200] {processor.py:153} INFO - Started process (PID=17592) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:57:21.091+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:57:21.092+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:57:21.092+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:57:21.111+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:57:21.110+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:57:21.112+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:57:21.111+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:57:21.112+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:57:21.124+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-26T21:58:06.851+0200] {processor.py:153} INFO - Started process (PID=17797) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:58:06.856+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:58:06.857+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:58:06.856+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:58:06.878+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:58:06.877+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:58:06.878+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:58:06.878+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:58:06.879+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:58:06.889+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-26T21:58:53.660+0200] {processor.py:153} INFO - Started process (PID=17902) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:58:53.668+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:58:53.668+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:58:53.668+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:58:53.686+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:58:53.686+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:58:53.686+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:58:53.686+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:58:53.687+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:58:53.695+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-03-26T21:59:42.097+0200] {processor.py:153} INFO - Started process (PID=18119) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:59:42.144+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T21:59:42.145+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:59:42.144+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:59:42.162+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:59:42.161+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T21:59:42.162+0200] {logging_mixin.py:137} INFO - [2023-03-26T21:59:42.162+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T21:59:42.162+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T21:59:42.171+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2023-03-26T22:00:28.826+0200] {processor.py:153} INFO - Started process (PID=18170) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:00:28.830+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:00:28.831+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:00:28.831+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:00:28.846+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:00:28.845+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:00:28.846+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:00:28.846+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:00:28.846+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:00:28.853+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-03-26T22:01:12.959+0200] {processor.py:153} INFO - Started process (PID=18255) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:01:12.975+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:01:12.976+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:01:12.976+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:01:12.990+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:01:12.990+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:01:12.990+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:01:12.990+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:01:12.990+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:01:12.997+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-26T22:02:01.913+0200] {processor.py:153} INFO - Started process (PID=18510) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:02:01.921+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:02:01.921+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:02:01.921+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:02:01.935+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:02:01.935+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:02:01.935+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:02:01.935+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:02:01.935+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:02:01.942+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-03-26T22:02:47.959+0200] {processor.py:153} INFO - Started process (PID=18567) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:02:47.978+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:02:47.979+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:02:47.979+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:02:47.997+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:02:47.997+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:02:47.997+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:02:47.997+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:02:47.998+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:02:48.007+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2023-03-26T22:03:33.910+0200] {processor.py:153} INFO - Started process (PID=18621) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:03:33.923+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:03:33.924+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:03:33.924+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:03:33.941+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:03:33.941+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:03:33.942+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:03:33.942+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:03:33.942+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:03:33.950+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-26T22:04:19.276+0200] {processor.py:153} INFO - Started process (PID=18681) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:04:19.277+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:04:19.278+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:04:19.277+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:04:19.292+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:04:19.292+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:04:19.292+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:04:19.292+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:04:19.292+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:04:19.299+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-03-26T22:05:04.284+0200] {processor.py:153} INFO - Started process (PID=18740) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:05:04.285+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:05:04.286+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:05:04.286+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:05:04.302+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:05:04.302+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:05:04.302+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:05:04.302+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:05:04.302+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:05:04.309+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-03-26T22:05:48.120+0200] {processor.py:153} INFO - Started process (PID=18791) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:05:48.121+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:05:48.122+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:05:48.122+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:05:48.140+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:05:48.139+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:05:48.140+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:05:48.140+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:05:48.140+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:05:48.147+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-03-26T22:06:34.152+0200] {processor.py:153} INFO - Started process (PID=18836) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:06:34.153+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:06:34.154+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:06:34.154+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:06:34.171+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:06:34.171+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:06:34.172+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:06:34.171+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:06:34.172+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:06:34.179+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-03-26T22:07:21.320+0200] {processor.py:153} INFO - Started process (PID=18982) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:07:21.336+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:07:21.336+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:07:21.336+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:07:21.355+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:07:21.354+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:07:21.355+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:07:21.355+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:07:21.355+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:07:21.364+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-03-26T22:08:06.188+0200] {processor.py:153} INFO - Started process (PID=19026) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:08:06.188+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:08:06.189+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:08:06.189+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:08:06.205+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:08:06.204+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:08:06.205+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:08:06.205+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:08:06.205+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:08:06.212+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-03-26T22:08:52.399+0200] {processor.py:153} INFO - Started process (PID=19112) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:08:52.399+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:08:52.400+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:08:52.400+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:08:52.414+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:08:52.413+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:08:52.414+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:08:52.414+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:08:52.414+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:08:52.421+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-03-26T22:09:40.372+0200] {processor.py:153} INFO - Started process (PID=19156) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:09:40.390+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:09:40.390+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:09:40.390+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:09:40.408+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:09:40.408+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:09:40.409+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:09:40.409+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:09:40.409+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:09:40.418+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-03-26T22:10:23.712+0200] {processor.py:153} INFO - Started process (PID=19215) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:10:23.713+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:10:23.714+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:10:23.714+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:10:23.731+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:10:23.731+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:10:23.732+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:10:23.731+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:10:23.732+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:10:23.739+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-03-26T22:11:11.309+0200] {processor.py:153} INFO - Started process (PID=19329) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:11:11.322+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:11:11.323+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:11:11.323+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:11:11.337+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:11:11.336+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:11:11.337+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:11:11.337+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:11:11.337+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:11:11.345+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-03-26T22:11:57.340+0200] {processor.py:153} INFO - Started process (PID=19371) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:11:57.341+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:11:57.341+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:11:57.341+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:11:57.355+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:11:57.355+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:11:57.355+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:11:57.355+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:11:57.356+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:11:57.362+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-03-26T22:12:40.941+0200] {processor.py:153} INFO - Started process (PID=19482) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:12:40.946+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:12:40.946+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:12:40.946+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:12:40.961+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:12:40.960+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:12:40.961+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:12:40.961+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:12:40.961+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:12:40.968+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-03-26T22:13:29.116+0200] {processor.py:153} INFO - Started process (PID=19525) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:13:29.134+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:13:29.135+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:13:29.135+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:13:29.154+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:13:29.153+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:13:29.154+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:13:29.154+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:13:29.155+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:13:29.163+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-03-26T22:14:16.165+0200] {processor.py:153} INFO - Started process (PID=19570) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:14:16.169+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:14:16.169+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:14:16.169+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:14:16.186+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:14:16.186+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:14:16.187+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:14:16.187+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:14:16.187+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:14:16.198+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-26T22:15:02.051+0200] {processor.py:153} INFO - Started process (PID=19619) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:15:02.057+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:15:02.058+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:15:02.057+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:15:02.072+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:15:02.071+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:15:02.072+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:15:02.072+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:15:02.072+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:15:02.080+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-03-26T22:15:49.811+0200] {processor.py:153} INFO - Started process (PID=19725) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:15:49.821+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:15:49.822+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:15:49.822+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:15:49.840+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:15:49.839+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:15:49.840+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:15:49.840+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:15:49.840+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:15:49.848+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-26T22:16:39.972+0200] {processor.py:153} INFO - Started process (PID=19833) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:16:40.043+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:16:40.044+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:16:40.043+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:16:40.059+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:16:40.058+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:16:40.059+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:16:40.059+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:16:40.060+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:16:40.069+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2023-03-26T22:17:26.952+0200] {processor.py:153} INFO - Started process (PID=19885) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:17:26.971+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:17:26.972+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:17:26.972+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:17:26.990+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:17:26.989+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:17:26.990+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:17:26.990+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:17:26.990+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:17:26.998+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-03-26T22:18:11.409+0200] {processor.py:153} INFO - Started process (PID=19993) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:18:11.425+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:18:11.426+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:18:11.426+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:18:11.440+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:18:11.439+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:18:11.440+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:18:11.440+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:18:11.440+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:18:11.447+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-26T22:18:55.838+0200] {processor.py:153} INFO - Started process (PID=20038) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:18:55.846+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:18:55.847+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:18:55.846+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:18:55.861+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:18:55.861+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:18:55.861+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:18:55.861+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:18:55.861+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:18:55.868+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-26T22:19:41.288+0200] {processor.py:153} INFO - Started process (PID=20147) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:19:41.343+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:19:41.344+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:19:41.344+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:19:41.358+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:19:41.357+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:19:41.358+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:19:41.358+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:19:41.358+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:19:41.365+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2023-03-26T22:20:25.995+0200] {processor.py:153} INFO - Started process (PID=20192) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:20:26.006+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:20:26.006+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:20:26.006+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:20:26.020+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:20:26.020+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:20:26.020+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:20:26.020+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:20:26.021+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:20:26.027+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-26T22:21:10.599+0200] {processor.py:153} INFO - Started process (PID=20282) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:21:10.600+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:21:10.600+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:21:10.600+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:21:10.614+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:21:10.614+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:21:10.614+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:21:10.614+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:21:10.614+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:21:10.621+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-03-26T22:21:56.159+0200] {processor.py:153} INFO - Started process (PID=20326) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:21:56.160+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:21:56.161+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:21:56.160+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:21:56.175+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:21:56.174+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:21:56.175+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:21:56.175+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:21:56.175+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:21:56.182+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-03-26T22:22:42.036+0200] {processor.py:153} INFO - Started process (PID=20369) to work on /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:22:42.049+0200] {processor.py:743} INFO - Processing file /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-26T22:22:42.050+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:22:42.050+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:22:42.067+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:22:42.067+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-26T22:22:42.068+0200] {logging_mixin.py:137} INFO - [2023-03-26T22:22:42.068+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-26T22:22:42.068+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-26T22:22:42.075+0200] {processor.py:175} INFO - Processing /home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
